---
# URL specifying the connection to the database. For example:
#   * tinydb: tinydb:////home/user/database.tinydb
#   * sqlite: sqlite:////home/user/mydb.sqlite
#   * mysql: mysql://scott:tiger@localhost/mydatabase
database_url: tinydb://~/.local/share/pynbox/database.tinydb

# Maximum time to process an element. A warning will be shown if it takes you
# longer.
max_time: 120

# List of element types. Each element can define:
#   * regexp: non capturing regular expression that identifies it
#   * priority: type priority, by default 3.
types:
  task:
    regexp: t\.
    priority: 4
  idea:
    regexp: i\.
